package cn.edu.sustech.cs209.chatting.common;

public enum ResponseType {
  TEXT,
  TOSENDFILE,
  RECEIVEFILE,
  LOGIN,
  LOGOUT,
  CHAT,
  GETUSERLIST,
  SENDMESSAGE,
  SENDGROUPMESSAGE,
  SENDFILE,
  GETFILE,
  PRESENDFILE,
  GETHISTORYMESSAGE,
  READYTORECEIVEFILE
}
